### ISSUE TITLE
В чём смысл этих методов?

### ISSUE THREAD

**Issue by coursar** [AliAlievALive/houseService#5]
https://github.com/AliAlievALive/houseService/blob/5c237b14b94ccca9dc5fe00897653d1a026948f0/src/main/java/ru/itpark/service/HouseService.java#L27-L59

**Comment by AliAlievALive** [comment]
Я думал надо вывести весь список объектов упорядоченный по цене

**Comment by coursar** [comment]
Для этого достаточно сделать просто:
```java
List<House> result = new ArrayList<>(houses);
result.sort(-> comparator <-);
return result;
```
